using CsSerializerGenerator.GeneratorLibrary;
using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;

namespace CsSerializerGenerator
{
    [Generator]
    public class EnumGenerator : Generator
    {
        public override void Excecute()
        {
            //Debugger.Launch();

            // for debug only
            CreateDebug();

            // get all classes with [Model] 
            foreach (var cl in GetAllClassesWithAttribute("CentralStationWebApi.Serializer.EnumConverterAttribute"))
            {
                CreateSerializerFile(cl);
                //CreateModelFile(cl);
                //CreateCastFile(cl);
            }
        }

        private void CreateSerializerFile(Class cl)
        {
            StringBuilder sb = new(
                $$"""
                // <auto-generated />

                #nullable enable annotations
                #nullable disable warnings

                // Suppress warnings about [Obsolete] member usage in generated code.
                #pragma warning disable CS0612, CS0618

                namespace {{cl.NameSpace}};

                partial class {{cl.Name}} : ICsSerialize
                {
                    public ICsSerialize? DeserializeLeave(string name)
                    {
                        switch (name)
                        {

                """);

            //AddLeaves(sb, cl);

            sb.AppendLine(
                $$"""
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} section {name}");
                            return null;
                        }
                    }

                    public void DeserializeProperty(string name, string value)
                    {
                        switch (name)
                        {
                """);

            //AddProperties(sb, cl);

            sb.AppendLine(
                $$"""
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} property {name}");
                            break;
                        }
                    }
                }
                """);

            AddSource($"{cl.Name}.g.cs", sb.ToString());
        }
    }
}
