using CsSerializerGenerator.GeneratorLibrary;
using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;

namespace CsSerializerGenerator
{
    [Generator]
    public class SerializeGenerator : Generator
    {
        public override void Excecute()
        {
            //Debugger.Launch();

            // for debug only
            CreateDebug();

            // get all classes with [Model] 
            foreach (var cl in GetAllClassesWithAttribute("CentralStationWebApi.Serializer.CsSerializeAttribute"))
            {
                CreateSerializerFile(cl);
                //CreateModelFile(cl);
                //CreateCastFile(cl);
            }
        }

        private void CreateSerializerFile(Class cl)
        {
            StringBuilder sb = new(
                $$"""
                // <auto-generated />

                #nullable enable annotations
                #nullable disable warnings

                // Suppress warnings about [Obsolete] member usage in generated code.
                #pragma warning disable CS0612, CS0618

                namespace {{cl.NameSpace}};

                partial class {{cl.Name}} : ICsSerialize
                {
                    public ICsSerialize? DeserializeLeave(string name)
                    {
                        switch (name)
                        {

                """);

            AddLeaves(sb, cl);

            sb.AppendLine(
                $$"""
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} section {name}");
                            return null;
                        }
                    }

                    public void DeserializeProperty(string name, string value)
                    {
                        switch (name)
                        {
                """);

            AddProperties(sb, cl);

            sb.AppendLine(
                $$"""
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} property {name}");
                            break;
                        }
                    }
                }
                """);

            AddSource($"{cl.Name}.g.cs", sb.ToString());
        }

        private void AddLeaves(StringBuilder sb, Class cl)
        {
            foreach (var prop in cl.Properties.Where(p => p.HasAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")))
            {
                var arg = prop.GetAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")?.ConstructorArguments.First();
                if (arg == null) continue;

                //sb.AppendLine($"// {prop.Name} - {prop.Type.Name} - {prop.Type.FullName} - {prop.Type.TypeKind} || {prop.Type.BaseTypeName} - {prop.Type.BaseTypeFullName}");

                if (prop.Type.TypeKind == TypeKind.Class)
                {
                    if (prop.Type.Name == "List")
                    {
                        sb.AppendLine($"        case {arg.Value}:");
                        sb.AppendLine($"            {prop.Name} ??= [];");
                        sb.AppendLine($"            var {LowercaseFirst(prop.Name)} = new {prop.Type.BaseTypeName}();");
                        sb.AppendLine($"            {prop.Name}.Add({LowercaseFirst(prop.Name)});");
                        sb.AppendLine($"            return {LowercaseFirst(prop.Name)};");
                    }
                    else if (prop.Type.FullName == "string" || prop.Type.FullName == "string?")
                    {
                        // do nothing
                    }
                    else
                    {
                        sb.AppendLine($"        case {arg.Value}:");
                        sb.AppendLine($"            return {prop.Name} = new {prop.Type.Name}();");
                    }
                }
            }
        }

        private void AddProperties(StringBuilder sb, Class cl)
        {
            foreach (var prop in cl.Properties.Where(p => p.HasAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")))
            {
                var arg = prop.GetAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")?.ConstructorArguments.First();
                if (arg == null) continue;

                switch (prop.Type.FullName)
                {
                case "List":
                    //sb.AppendLine($"// List {prop.Name} {prop.Type.FullName}");
                    break;
                case "string?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = value;");
                    sb.AppendLine("            break;");
                    break;
                case "int":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToInt(value);");
                    sb.AppendLine("            break;");
                    break;
                case "uint":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUInt(value);");
                    sb.AppendLine("            break;");
                    break;
                case "List<int>":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "List<uint>":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "int[]?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "uint[]?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUIntArray(value);");
                    sb.AppendLine("            break;");
                    break;

                default:
                    //sb.AppendLine($"// {prop.Name} - {prop.Type.Name} - {prop.Type.FullName} not defined");
                    break;
                }                   
                    
            }
        }

        private string LowercaseFirst(string input)
        {
            if (string.IsNullOrEmpty(input) || char.IsLower(input[0]))
                return input;
            return char.ToLower(input[0]) + input.Substring(1);
        }
    }
}

    
