using Microsoft.CodeAnalysis;
using System.Diagnostics.Contracts;
using System.Reflection.Metadata;
using System.Text;
using CsSerializerGenerator.GeneratorLibrary;
using System.Linq;

namespace CsSerializerGenerator
{
    [Generator]
    public class SerializeGenerator : Generator
    {
        public override void Excecute()
        {
            //Debugger.Launch();

            // for debug only
            CreateDebug();

            // get all classes with [Model] 
            foreach (var cl in GetAllClassesWithAttribute("CentralStationWebApi.Serializer.CsSerializeAttribute"))
            {
                CreateSerializerFile(cl);
                //CreateModelFile(cl);
                //CreateCastFile(cl);
            }
        }

        private void CreateSerializerFile(Class cl)
        {
            StringBuilder sb = new(
                $$"""
                // <auto-generated />

                #nullable enable annotations
                #nullable disable warnings

                // Suppress warnings about [Obsolete] member usage in generated code.
                #pragma warning disable CS0612, CS0618

                namespace {{cl.NameSpace}};

                partial class {{cl.Name}} : ICsSerialize
                {
                    public ICsSerialize? DeserializeLeave(string name)
                    {
                        switch (name)
                        {

                """);

            AddLeaves(sb, cl);

            sb.AppendLine(
                $$"""
                        
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} section {name}");
                            return null;
                        }
                    }

                    public void DeserializeProperty(string name, string value)
                    {
                        switch (name)
                        {
                """);

            AddProperties(sb, cl);

            sb.AppendLine(
                $$"""
                        default:
                            Debug.WriteLine($"Unknown {{cl.Name}} property {name}");
                            break;
                        }
                    }
                }
                """);

            AddSource($"{cl.Name}.g.cs", sb.ToString());
        }

        private void AddLeaves(StringBuilder sb, Class cl)
        {
            foreach (var prop in cl.Properties.Where(p => p.HasAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")))
            {
                
                var attr = prop.GetAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute");
                var arg = attr!.ConstructorArguments.First();
                sb.AppendLine($"            case {arg.Value}:");
                sb.AppendLine("                break;");
            }
        }

        private void AddProperties(StringBuilder sb, Class cl)
        {
            foreach (var prop in cl.Properties.Where(p => p.HasAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")))
            {
                var arg = prop.GetAttribute("CentralStationWebApi.Serializer.CsPropertyAttribute")?.ConstructorArguments.First();
                if (arg == null) continue;

                switch (prop.Type.FullName)
                {
                case "List":
                    sb.AppendLine($"// List {prop.Name} {prop.Type.FullName}");
                    break;
                case "string?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = value;");
                    sb.AppendLine("            break;");
                    break;
                case "int":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToInt(value);");
                    sb.AppendLine("            break;");
                    break;
                case "uint":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUInt(value);");
                    sb.AppendLine("            break;");
                    break;
                case "List<int>":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "List<uint>":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "int[]?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToIntArray(value);");
                    sb.AppendLine("            break;");
                    break;
                case "uint[]?":
                    sb.AppendLine($"        case {arg.Value}:");
                    sb.AppendLine($"            {prop.Name} = CsSerializer.ToUIntArray(value);");
                    sb.AppendLine("            break;");
                    break;

                default:
                    sb.AppendLine($"// {prop.Name} - {prop.Type.Name} - {prop.Type.FullName} not defined");
                    break;
                }                   
                    
            }
        }

        

        private void CreateModelFile(Class cl)
        {
            StringBuilder sb = new(
                $$"""
                // <auto-generated />

                #nullable enable annotations
                #nullable disable warnings

                // Suppress warnings about [Obsolete] member usage in generated code.
                #pragma warning disable CS0612, CS0618

                namespace {{cl.NameSpace}}.Model;
                    
                internal partial class {{cl.Name}}ModelTest
                {
                """);

            foreach (var prop in cl.Properties)
            {
                string jsonName = LowercaseFirst(prop.Name);
                string typeName = TypeName(prop.Type);
                string propName = prop.Name;
               
                sb.AppendLine(
                    $$"""

                        //[JsonPropertyName("{{jsonName}}")]
                        public {{typeName}} {{propName}} { get; set; }
                    """);
            }

            sb.AppendLine("}");
            AddSource($"{cl.Name}ModelTest.g.cs", sb.ToString());
        }

        private void CreateCastFile(Class cl)
        {
            StringBuilder sb = new(
                $$"""
                // <auto-generated />

                #nullable enable annotations
                #nullable disable warnings
                
                // Suppress warnings about [Obsolete] member usage in generated code.
                #pragma warning disable CS0612, CS0618

                namespace {{cl.NameSpace}}.Model;
                    
                internal static class {{cl.Name}}Cast
                {
                    public static {{cl.Name}} CastTo(this {{cl.Name}}Model model)
                    {
                        return new {{cl.Name}}()
                        {

                """);

            foreach (var prop in cl.Properties)
            {
                if (IsLocal(prop.Type))
                {
                    sb.AppendLine($"            {prop.Name} = model.{prop.Name}?.CastTo(),");
                }
                else
                {                    
                    sb.AppendLine($"            {prop.Name} = model.{prop.Name},"); 
                }
            }
                
            sb.AppendLine(
                $$"""
                        };
                    }
                    
                    public static {{cl.Name}}Model CastFrom(this {{cl.Name}} item)
                    {
                        return new {{cl.Name}}Model()
                        {
                """);

            foreach (var prop in cl.Properties)
            {
                if (IsLocal(prop.Type))
                {
                    sb.AppendLine($"            {prop.Name} = item.{prop.Name}?.CastFrom(),");
                }
                else
                {
                    sb.AppendLine($"            {prop.Name} = item.{prop.Name},");
                }
            }
            
            sb.AppendLine(
                $$"""
                        };
                    }
                """);
            

            sb.AppendLine("}");
            AddSource($"{cl.Name}Cast.g.cs", sb.ToString());
        }


        private string LowercaseFirst(string input)
        {
            if (string.IsNullOrEmpty(input) || char.IsLower(input[0]))
                return input;
            return char.ToLower(input[0]) + input.Substring(1);
        }

        private string TypeName(TypeSym type)
        {
            return type.FullName switch
            {
                "bool" => "bool",
                "bool?" => "bool?",
                "int" => "int",
                "int?" => "int?",
                "string" => "string",
                "string?" => "string?",
                "System.DateTime" => "System.DateTime",
                "System.DateTime?" => "System.DateTime?",
                _ => $"{type.Name}Model?"
            };


        }

        private bool IsLocal(TypeSym type)
        {
            return type.FullName switch
            {
                "bool" => false,
                "bool?" => false,
                "int" => false,
                "int?" => false,
                "string" => false,
                "string?" => false,
                "System.DateTime" => false,
                "System.DateTime?" => false,
                _ => true
            };
        }
    }
}
    
