namespace CentralStationApi.Serializer;


/// <summary>
/// Defines methods for deserializing Central Station configuration data.
/// Implemented by classes that can be deserialized from the CS2/CS3 file format.
/// </summary>
/// <remarks>
/// This interface is typically implemented by model classes decorated with <c>[CsSerialize]</c> attribute.
/// The implementation is automatically generated by the source generator to handle the custom
/// Central Station text-based configuration format.
/// </remarks>
public interface ICsSerialize
{
    /// <summary>
    /// Called when leaving a nested section during deserialization.
    /// </summary>
    /// <param name="line">The name of the section being exited.</param>
    /// <returns>
    /// An <see cref="ICsSerialize"/> implementation to handle the nested section data,
    /// or a dummy implementation if the section is not recognized.
    /// </returns>
    /// <remarks>
    /// This method is invoked by the deserializer when encountering nested data structures
    /// in the Central Station configuration format. For unknown sections, implementations
    /// typically return a <c>CsDummy</c> instance to gracefully skip unrecognized data.
    /// </remarks>
    ICsSerialize DeserializeLeave(string line);

    /// <summary>
    /// Deserializes a single property from the configuration data.
    /// </summary>
    /// <param name="name">The name of the property as it appears in the configuration file.</param>
    /// <param name="value">The string value to deserialize and assign to the property.</param>
    /// <remarks>
    /// This method maps Central Station property names to .NET properties. The property name
    /// is typically specified using the <c>[CsProperty]</c> attribute on the target property.
    /// Implementations should handle type conversion from string to the appropriate property type.
    /// </remarks>
    void DeserializeProperty(string name, string value);
}

